DROP VIEW IF EXISTS order_queue_view;
ALTER TABLE commission_entries DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS commission_entries_actor_scope ON commission_entries;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS orders_public_capture_insert ON orders;
DROP POLICY IF EXISTS orders_actor_scope ON orders;
DROP TRIGGER IF EXISTS integrations_touch_updated ON integrations;
DROP TRIGGER IF EXISTS tasks_touch_updated ON tasks;
DROP TRIGGER IF EXISTS support_cases_touch_updated ON support_cases;
DROP TRIGGER IF EXISTS customers_touch_updated ON customers;
DROP TRIGGER IF EXISTS orders_touch_updated ON orders;
DROP FUNCTION IF EXISTS touch_updated_at();
DROP TRIGGER IF EXISTS webhook_events_no_delete ON webhook_events;
DROP TRIGGER IF EXISTS audit_events_immutable ON audit_events;
DROP TRIGGER IF EXISTS gift_card_entries_immutable ON gift_card_entries;
DROP TRIGGER IF EXISTS commission_entries_immutable ON commission_entries;
DROP TRIGGER IF EXISTS gift_card_status_history_immutable ON gift_card_status_history;
DROP TRIGGER IF EXISTS commission_status_history_immutable ON commission_status_history;
DROP TRIGGER IF EXISTS operator_status_history_immutable ON operator_status_history;
DROP TRIGGER IF EXISTS order_status_history_immutable ON order_status_history;
DROP TRIGGER IF EXISTS order_conversation_archive_messages_immutable ON order_conversation_archive_messages;
DROP TRIGGER IF EXISTS order_conversation_archives_immutable ON order_conversation_archives;
DROP TRIGGER IF EXISTS order_snapshots_immutable ON order_snapshots;
DROP TRIGGER IF EXISTS conversation_messages_immutable ON conversation_messages;
DROP FUNCTION IF EXISTS prevent_immutable_change();
